import { useEffect,useState } from "react";
import { useLocation,useRoute } from "wouter";
type Student={id:string;firstName:string;preferredName:string|null;gradeLevel:string;learningStyle:string;interests:string|null};
const options=["Language Arts","Mathematics","Science","Social Studies","Art & Design","Music","Physical Education","Life Skills"];
export default function CurriculumSetupPage(){const [,p]=useRoute("/students/:id/curriculum");const [,go]=useLocation();const [student,setStudent]=useState<Student|null>(null);const [subjects,setSubjects]=useState(["Language Arts","Mathematics","Science","Social Studies"]);const [term,setTerm]=useState("2026–27 School Year");const [days,setDays]=useState("4");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{fetch(`/api/students/${p?.id}`).then(r=>r.ok?r.json():Promise.reject()).then(setStudent).catch(()=>setError("Could not load learner profile"))},[p?.id]);
 const toggle=(x:string)=>setSubjects(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);
 async function create(){if(!student||!subjects.length)return;setBusy(true);setError("");try{for(const subject of subjects){const r=await fetch("/api/courses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:subject,subject,gradeLevel:student.gradeLevel,description:`${term} curriculum for ${student.preferredName||student.firstName}. Planned for ${days} learning days per week.`})});if(!r.ok)throw new Error()}go("/courses")}catch{setError("We couldn't create the curriculum. Please try again.")}finally{setBusy(false)}}
 const name=student?.preferredName||student?.firstName||"your learner";
 return <div className="flex-1 animate-in fade-in duration-300"><div className="grid grid-cols-12 border-b border-black"><div className="col-span-12 md:col-span-8 p-6 md:p-10 border-b md:border-b-0 md:border-r border-black"><span className="label-caps text-[#777]">Curriculum setup</span><h1 className="mt-5 text-4xl md:text-6xl font-bold uppercase leading-[.95] tracking-[-.04em]">Build {name}’s<br/>starting plan.</h1></div><div className="col-span-12 md:col-span-4 p-6 md:p-8 flex flex-col justify-between gap-10"><span className="label-caps">Step 02 / 02</span><p className="text-sm leading-6 text-[#666]">Choose the foundation now. Each subject becomes an editable draft course.</p></div></div>
 <div className="grid grid-cols-12"><aside className="col-span-12 md:col-span-3 p-6 md:p-8 border-b md:border-b-0 md:border-r border-black"><span className="label-caps">Learner profile</span>{student&&<div className="mt-6"><p className="text-xl font-bold uppercase">{name}</p><p className="mt-2 text-xs text-[#777] uppercase tracking-wider">{student.gradeLevel} · {student.learningStyle}</p>{student.interests&&<p className="mt-6 text-sm leading-6">Interested in {student.interests}.</p>}</div>}</aside><main className="col-span-12 md:col-span-9 p-6 md:p-10 space-y-10">
 <section><h2 className="label-caps mb-5">01 · Schedule frame</h2><div className="grid sm:grid-cols-2 gap-5"><label className="text-xs uppercase tracking-wider">Academic term<input value={term} onChange={e=>setTerm(e.target.value)} className="mt-2 w-full border border-black p-3 text-sm outline-none"/></label><label className="text-xs uppercase tracking-wider">Learning days / week<select value={days} onChange={e=>setDays(e.target.value)} className="mt-2 w-full border border-black p-3 text-sm outline-none">{[3,4,5].map(x=><option key={x}>{x}</option>)}</select></label></div></section>
 <section className="pt-8 border-t border-black"><div className="flex justify-between mb-5"><h2 className="label-caps">02 · Starting subjects</h2><span className="label-caps text-[#777]">{subjects.length} selected</span></div><div className="grid sm:grid-cols-2 gap-px bg-black border border-black">{options.map((x,i)=><button key={x} onClick={()=>toggle(x)} className={`p-5 text-left bg-white hover:bg-[#eee] flex justify-between ${subjects.includes(x)?"!bg-black text-white":""}`}><span className="text-sm font-semibold uppercase">{String(i+1).padStart(2,"0")} · {x}</span><span>{subjects.includes(x)?"✓":"+"}</span></button>)}</div></section>
 <section className="pt-8 border-t border-black"><h2 className="label-caps mb-3">What happens next</h2><p className="text-sm leading-6 text-[#666] max-w-xl">We’ll create {subjects.length} draft {subjects.length===1?"course":"courses"}. From there, add units and lessons at your own pace.</p></section>{error&&<p className="bg-black text-white p-4 text-xs uppercase tracking-wider">{error}</p>}</main></div>
 <div className="border-t border-black grid grid-cols-12"><button onClick={()=>go("/students/new")} className="col-span-4 md:col-span-3 py-6 label-caps border-r border-black hover:bg-[#eee]">← Back</button><button onClick={create} disabled={busy||!subjects.length||!student} className="col-span-8 md:col-span-9 bg-black text-white py-6 uppercase text-xs font-semibold tracking-[.2em] hover:bg-white hover:text-black disabled:opacity-40">{busy?"Creating curriculum…":`Create ${subjects.length} draft courses →`}</button></div></div>
}
