import { useState } from "react";
import { useLocation } from "wouter";

const grades = ["Pre-K","Kindergarten","Grade 1","Grade 2","Grade 3","Grade 4","Grade 5","Grade 6","Grade 7","Grade 8","Grade 9","Grade 10","Grade 11","Grade 12"];
const styles = [{id:"visual",title:"Visual",note:"Diagrams, reading, demonstrations"},{id:"auditory",title:"Auditory",note:"Discussion, narration, listening"},{id:"hands-on",title:"Hands-on",note:"Projects, movement, experiments"},{id:"mixed",title:"Mixed",note:"A balanced blend of approaches"}];
export default function NewStudentPage() {
 const [,go]=useLocation(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const [form,setForm]=useState({firstName:"",lastName:"",preferredName:"",age:"",gradeLevel:"",learningStyle:"",interests:"",supportNotes:""});
 const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setBusy(true);try{const r=await fetch("/api/students",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not register student");go(`/students/${data.id}/curriculum`)}catch(e){setError(e instanceof Error?e.message:"Could not register student")}finally{setBusy(false)}}
 const field="w-full border border-black bg-white px-4 py-3 text-sm outline-none focus:bg-[#f3f3f3]";
 return <div className="flex-1 animate-in fade-in duration-300">
  <div className="grid grid-cols-12 border-b border-black"><div className="col-span-12 md:col-span-8 p-6 md:p-10 border-b md:border-b-0 md:border-r border-black"><span className="label-caps text-[#777]">Student onboarding</span><h1 className="mt-5 text-4xl md:text-6xl font-bold uppercase leading-[.95] tracking-[-.04em]">Let’s meet<br/>your learner.</h1></div><div className="col-span-12 md:col-span-4 p-6 md:p-8 flex flex-col justify-between gap-10"><span className="label-caps">Step 01 / 02</span><p className="text-sm leading-6 text-[#666]">Start with the person, not the plan. These details help shape a curriculum that fits how they learn.</p></div></div>
  <form onSubmit={submit}><div className="grid grid-cols-12"><aside className="col-span-12 md:col-span-3 p-6 md:p-8 border-b md:border-b-0 md:border-r border-black"><p className="label-caps">Required fields</p><p className="mt-3 text-xs leading-5 text-[#777]">You can refine interests and learning support at any time.</p></aside><div className="col-span-12 md:col-span-9 p-6 md:p-10 space-y-9">
   <section><h2 className="label-caps mb-5">01 · Basics</h2><div className="grid md:grid-cols-2 gap-5"><label className="text-xs uppercase tracking-wider">First name *<input autoFocus required value={form.firstName} onChange={e=>set("firstName",e.target.value)} className={field+" mt-2"}/></label><label className="text-xs uppercase tracking-wider">Last name *<input required value={form.lastName} onChange={e=>set("lastName",e.target.value)} className={field+" mt-2"}/></label><label className="text-xs uppercase tracking-wider">Preferred name<input value={form.preferredName} onChange={e=>set("preferredName",e.target.value)} className={field+" mt-2"} placeholder="If different"/></label><label className="text-xs uppercase tracking-wider">Age *<input required min="3" max="21" type="number" value={form.age} onChange={e=>set("age",e.target.value)} className={field+" mt-2"}/></label></div></section>
   <section className="pt-8 border-t border-black"><h2 className="label-caps mb-5">02 · Learning profile</h2><label className="text-xs uppercase tracking-wider block">Current level *<select required value={form.gradeLevel} onChange={e=>set("gradeLevel",e.target.value)} className={field+" mt-2"}><option value="">Select a level</option>{grades.map(x=><option key={x}>{x}</option>)}</select></label><div className="mt-6"><span className="text-xs uppercase tracking-wider">Learns best through *</span><div className="grid sm:grid-cols-2 gap-px bg-black border border-black mt-2">{styles.map(x=><button type="button" key={x.id} onClick={()=>set("learningStyle",x.id)} className={`text-left p-4 bg-white hover:bg-[#eee] ${form.learningStyle===x.id?"!bg-black text-white":""}`}><span className="block text-sm font-semibold uppercase">{x.title}</span><span className="block text-xs mt-1 opacity-60">{x.note}</span></button>)}</div></div></section>
   <section className="pt-8 border-t border-black"><h2 className="label-caps mb-5">03 · A little more</h2><div className="grid md:grid-cols-2 gap-5"><label className="text-xs uppercase tracking-wider">Interests<textarea value={form.interests} onChange={e=>set("interests",e.target.value)} className={field+" mt-2 min-h-28 resize-none"} placeholder="Space, drawing, animals..."/></label><label className="text-xs uppercase tracking-wider">Support notes<textarea value={form.supportNotes} onChange={e=>set("supportNotes",e.target.value)} className={field+" mt-2 min-h-28 resize-none"} placeholder="Pacing, accommodations, goals..."/></label></div></section>
   {error&&<p className="bg-black text-white p-4 text-xs uppercase tracking-wider">{error}</p>}
  </div></div><div className="border-t border-black grid grid-cols-12"><div className="hidden md:block md:col-span-3 border-r border-black"/><button disabled={busy||!form.learningStyle} className="col-span-12 md:col-span-9 bg-black text-white py-6 uppercase text-xs font-semibold tracking-[.2em] hover:bg-white hover:text-black disabled:opacity-40">{busy?"Registering learner…":"Register student & build curriculum →"}</button></div></form>
 </div>
}
